services:
    fts:
        image: freetakserver
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./data/:/opt/
            # relevant files:
        ports:
            # Data Package Port
            - 8080:8080
            # SSL Data Package Port
            - 8443:8443
            # CoT Port
            - 8087:8087
            # SSL CoT Port
            - 8089:8089
            # API port
            # - 19023:19023
            # UI port
            - 5000:5000
            # Map port
            - 8001:8000
        environment:
            - FTS_UI_EXPOSED_IP=0.0.0.0
            - FTS_UI_PORT=5000
            - FTS_IP=localhost
            - FTS_PORT=19023
            - FTS_MAP_EXPOSED_IP=10.5.0.3
